name: Angular CI

on:
  push:
    paths:
      - 'frontend/**'  # Cette partie surveille tous les changements dans le dossier frontend
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest  # Le workflow se déroulera sur une machine virtuelle Ubuntu
    defaults:
      run:
        working-directory: frontend  # Change de répertoire de travail pour le frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Cette étape récupère ton code source

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Utilise la version de Node.js 18

    - name: Install dependencies
      run: npm install  # Installe les dépendances du projet Angular

    - name: Build Angular project
      run: npm run build  # Lance la commande pour construire le projet Angular
